version: 2.1
executors:
  client:
    working_directory: './client'
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    executor: client
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test-client
